name: Sync to S3

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout the repository

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest
    environment: aws-env-vars  # Specify the environment here
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: ${{ github.workflow }}-${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }} --delete