name: Sync to S3 Stages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout the repository

jobs:
  sync-to-s3-stages:
    runs-on: ubuntu-latest
    environment: schulzry+release-center-test-339388639699
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: s3-sync-${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Sync files to S3 repo
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/stages/repo --delete

      - name: Sync files to S3 dev
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/stages/dev --delete

      - name: Sync files to S3 beta
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/stages/beta --delete
      
      - name: Sync files to S3 gamma
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/stages/beta --delete

      - name: Sync files to S3 prod
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/stages/beta --delete