name: Sync to S3 Stages


env:
  REPO_BUCKET_FOLDER: /stages/repo
  DEV_BUCKET_FOLDER: /stages/dev
  BETA_BUCKET_FOLDER: /stages/beta
  GAMMA_BUCKET_FOLDER: /stages/gamma
  PROD_BUCKET_FOLDER: /stages/prod


on:
  push:
    branches:
      - main  # or your default branch

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout the repository

jobs:
  sync-to-s3-repo:
    runs-on: ubuntu-latest
    environment: schulzry+release-center-test-339388639699
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: s3-sync-${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Sync files to S3 repo
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}${{ env.REPO_BUCKET_FOLDER }} --delete

  sync-repo-to-non-prod:
    runs-on: ubuntu-latest
    environment: schulzry+release-center-test-339388639699
    needs: sync-to-s3-repo
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          role-session-name: s3-sync-${{ github.run_id }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync repo to dev
        run: |
          aws s3 sync s3://${{ vars.S3_BUCKET_NAME }}${{ env.REPO_BUCKET_FOLDER }} s3://${{ vars.S3_BUCKET_NAME }}${{ env.DEV_BUCKET_FOLDER }} --delete

      - name: Sync files to S3 beta
        run: |
          aws s3 sync s3://${{ vars.S3_BUCKET_NAME }}${{ env.DEV_BUCKET_FOLDER }} s3://${{ vars.S3_BUCKET_NAME }}${{ env.BETA_BUCKET_FOLDER }} --delete

      - name: Sync files to S3 gamma
        run: |
          aws s3 sync s3://${{ vars.S3_BUCKET_NAME }}${{ env.BETA_BUCKET_FOLDER }} s3://${{ vars.S3_BUCKET_NAME }}${{ env.GAMMA_BUCKET_FOLDER }} --delete
      